team_assignments:
  "phoenix": "blue"
  "gryphon": "red"

quad_state_topics:
  "phoenix": "/phoenix/state"
  "gryphon": "/gryphon/state"

proposed_trajectory_topics:
  "phoenix": "/phoenix/proposed_trajectory"
  "gryphon": "/gryphon/proposed_trajectory"

updated_trajectory_topics:
  "phoenix": "/phoenix/updated_trajectory"
  "gryphon": "/gryphon/updated_trajectory"

map_file_path: "/home/tuckerhaydon/Workspace/MediationLayer/data/maps/arena.map"

quad_mesh_file_path: "file:///home/tuckerhaydon/Workspace/MediationLayer/resources/meshes/quad.stl"

balloon_mesh_file_path: "file:///home/tuckerhaydon/Workspace/MediationLayer/resources/meshes/balloon.stl"
