team_assignments:
  "phoenix": "blue"

quad_state_topics:
  "phoenix": "/phoenix/state"

proposed_trajectory_topics:
  "phoenix": "/phoenix/proposed_trajectory"

updated_trajectory_topics:
  "phoenix": "/phoenix/updated_trajectory"

balloon_status_topics:
  "red": "/game_engine/red_balloon_status"
  "blue": "/game_engine/blue_balloon_status"

map_file_path: "/home/aerial-robotics/Workspace/GameEngine/resources/maps/pretournament.map"
quad_mesh_file_path: "file:///home/aerial-robotics/Workspace/GameEngine/resources/meshes/quad.stl"
balloon_mesh_file_path: "file:///home/aerial-robotics/Workspace/GameEngine/resources/meshes/balloon.stl"

blue_balloon_position: [9, 4, 1]
red_balloon_position:  [9, 1, 1]

initial_quad_positions:
  "phoenix": "2 2 1"


