team_assignments:
  "phoenix": "blue"

quad_state_topics:
  "phoenix": "/phoenix/state"

proposed_trajectory_topics:
  "phoenix": "/phoenix/proposed_trajectory"

updated_trajectory_topics:
  "phoenix": "/phoenix/updated_trajectory"

map_file_path: "/home/aerial-robotics/Workspace/GameEngine/resources/maps/arena1.map"
quad_mesh_file_path: "file:///home/aerial-robotics/Workspace/GameEngine/resources/meshes/quad.stl"
balloon_mesh_file_path: "file:///home/aerial-robotics/Workspace/GameEngine/resources/meshes/balloon.stl"

blue_balloon_position: [9, 1, 1]
red_balloon_position:  [9, 4, 1]

initial_quad_positions:
  "phoenix": "2 2 1"

max_quadcopter_velocity: 2.0
max_quadcopter_acceleration: 0.4


